### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/r-socialsci#109]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [x] Example code chunks run as expected
- [x] Challenges / exercises run as expected
- [x] Challenge / exercise solutions are correct
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [x] Each episode includes key points
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided
- [x] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by juanfung** [comment]
@francois Everything should be okay now, except for a few exercises:

- Episode 3: "What was the largest household interviewed in each month?" produces an error, should be fixed by 6cab6a8934d51f82cd27b349175f41361130f549
- Episode 3: the exercises under the "Applying spread() to clean our data" aren't rendering correctly, but the problems appear to be fixed in the rmd files

Also, there's an issue with regard to subsetting data frames vs tibbles #110

**Comment by ErinBecker** [comment]
Thanks for the update @juanfung. Later this week, we'll be putting out a blog post and some tweets calling for contributions to lessons that are preparing for publication. We'll be directing contributors towards issues that are grouped in the "June 2019 Milestone". Could you please tag any issues that you'd like contributions towards as part of that milestone? Thanks much and let me and @fmichonneau know if there's anything you need help with from the technical / lesson rendering side!

**Comment by ErinBecker** [comment]
Hey @juanfung - just checking in to see if you're still planning on joining the release this month. We're asking that all lessons have completed the checklist by [Tuesday, 4 June, Anywhere on Earth time] (https://www.timeanddate.com/worldclock/fixedtime.html?iso=20190604T235959&p1=3399) in order to be included in the release. Please let me and @fmichonneau know if you have any questions or are running into any technical issues with preparing your lesson.

**Comment by juanfung** [comment]
Hi @ErinBecker I just looked over the two errors I mentioned above and the second one is still producing an error. I will try to fix it as soon as I have a chance (or maybe @angela-li could take a look!). Once that's resolved, the lesson should be ready for release!

**Comment by juanfung** [comment]
@erin and @francois: I pushed a commit that should take care of the issue above 
> Episode 3: the exercises under the "Applying spread() to clean our data" aren't rendering correctly
Once this update is rendered, we should be good to go.

I'll wait to confirm it's rendered correctly before checking off the last item on the release checklist

**Comment by juanfung** [comment]
This lesson is ready!

**Comment by angela-li** [comment]
Looks great Juan, thanks for taking care of this!

**Comment by ErinBecker** [comment]
Awesome work @juanfung @angela-li and everyone else who contributed! This is just a quick message confirming that this lesson will be included in the release that @fmichonneau and I are preparing this week. The release is scheduled to go through on the 18th and to be announced to the community on the 24th. Please let us know if you have any questions! And congratulations again!

**Comment by fmichonneau** [comment]
lesson released! :tada: https://doi.org/10.5281/zenodo.3265729 Thank you all for your work on this!
