### ISSUE TITLE
Use of travis to build and deploy the lesson website

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/r-socialsci#116]
I've enabled travis CI to build and deploy the lesson website for this repository. Because of this change, the new default branch for the repository isn't `gh-pages` but `master`. `gh-pages` is now only used to push the built website by Travis. Any manual modification to `gh-pages` will be deleted during the next build. 

Make sure that you create pull requests against `master` from now on.

Let me know if you have any questions!

**Comment by juanfung** [comment]
Thanks @fmichonneau !

**Comment by pkiraly** [comment]
Dear @fmichonneau and @angela-li,

The contribution guide (https://github.com/datacarpentry/r-socialsci/blob/gh-pages/CONTRIBUTING.md) describes it differently

"The published copy of the lesson is in the gh-pages branch of the repository (so that GitHub will regenerate it automatically). Please create all branches from that, and merge the master repository's gh-pages branch into your gh-pages branch before starting work."

If this policy was changed I think the Contributing page should mirror this change, you can not expect that every contributor will read this ticket.

**Comment by fmichonneau** [comment]
@pkiraly thanks for bringing this up! Would you be willing/able to submit a pull request with the needed change?

**Comment by pkiraly** [comment]
@fmichonneau 

I did, see #142.

**Comment by jonjab** [comment]
With this change, should I be forking the master branch instead of gh_pages when following the instructions here:

https://github.com/dmgt/swc_github_flow/blob/master/for_novice_contributors.md#option-2---use-a-command-line-interface-with-git

And if I do that, should previewing locally using jekyll work, or does travis change that as well?

**Comment by juanfung** [comment]
@jonjab Yes please fork from master. Serving locally on jekyll should work as expected (in principle)

**Comment by kelseygonzalez** [comment]
@juanfung It seems like issue has been 'solved'. Should we close the issue or leave it open and pinned for new contributors?

**Comment by juanfung** [comment]
I think we can close it, since it's noted in the contributing guide
