### ISSUE TITLE
Include graphics to visually illustrate the concepts of spread/gather

### ISSUE THREAD

**Issue by angela-li** [datacarpentry/r-socialsci#125]
It would be useful to include in the Figures / lesson a visual representation of spread/gather (or pivot longer/pivot wider) so that learners could create a mental model of how reshaping works

**Comment by ErinBecker** [comment]
Great idea @angela-li! The DC Ecology R lesson has a figure for this that you could use or adapt. I don't remember if it uses the variable names that are for the data in that lesson or not . . .

**Comment by bryanhong8** [comment]
I think this would also be helpful to learners @angela-li & @ErinBecker! I was trying to adapt the figure from the DC Ecology R lesson (which uses the variable names from the data in that lesson), but was there were a few things that I ran into that might lead to difficulties in understanding the figure. The DC lesson uses an intermediary data frame with all the transformations already done prior to spreading it (rather than having them all in one line), which is referenced in the figure, so having something similar might make the figure easier to understand. Also, the current first example uses a dummy column with only TRUE values, so some learners may have trouble differentiating how spread/gather treats the different values -- maybe having a different example would make it easier for learners to visualize? Let me know what you think!

**Comment by ErinBecker** [comment]
Thanks for this suggestion @bryanhong8. I haven't been actively involved in the development on this lesson for the past year or so, so I'll let @angela-li and @juanfung take the lead on directing effort here. 🙂

**Comment by katrinleinweber** [comment]
[tidyr published their .key source files](https://github.com/tidyverse/tidyr/tree/master/vignettes), which might be helpful when implementing this + #104.

**Comment by maczokni** [comment]
Hiya!
I've made a similar image before for my summer school material, so I've used that to try to re-create the ecology r lesson one, hope it's what you were after?

**Comment by juanfung** [comment]
Thanks @maczokni ! I've merged your PR. @angela-li @bryanhong8 does this look good to you guys?

**Comment by ha0ye** [comment]
@gadenbuie also has a few animations up at https://www.garrickadenbuie.com/project/tidyexplain/

**Comment by juanfung** [comment]
This has been resolved (and images have been updated #163)
