### ISSUE TITLE
reading in 1 csv vs multiple csv

### ISSUE THREAD

**Issue by johnnydubois13** [datacarpentry/r-socialsci#127]
In 03-Starting with Data, the motivating question is "How can I read a complete csv file into R?". This is obviously a critical thing to learn, but I often find myself wanting to read in an entire folder of csv files (where each subject has their own csv). This is definitely more complicated than a single read.csv or read_csv call, but is it maybe worth mentioning, or including as an example in later episodes?

**Comment by angela-li** [comment]
Thanks for the idea! I'm not sure it fits into the scope of the lesson as it stands, but you make a great point that it's important for researchers to bulk-read csvs - I myself have had to do that many a time! Since we're just working with one dataset in the workshop, I think it makes sense to limit what we include in the curriculum to what will be immediately useful in the workshop, as there's already so much material for new learners to digest. (However, that doesn't limit you from showcasing how to read in multiple csvs when you teach this workshop. I think showing how you as a researcher "in the wild" use this stuff can be extremely helpful!)

I'm curious, what do you usually do to read in multiple csvs? I've used purrr before, but perhaps you have a different workflow?

**Comment by johnnydubois13** [comment]
That's a good point. Upon more reflection it is probably a better idea for the lesson to go from simple to complex.

I recently started using purrr, but I have also tried writing my own very basic function, or gone the apply route. Can't say I have a consistent favourite.

**Comment by angela-li** [comment]
Nice! Yes, I was a big apply user before I realized purrr had the same functionality. I'm closing this issue for now, but thanks for the idea. Good luck teaching this workshop, and please report anything you find from teaching it.
