### ISSUE TITLE
Compute item proportions using `summarize_at()`

### ISSUE THREAD

**Issue by ha0ye** [datacarpentry/r-socialsci#193]
In the ggplot episode, the code computes the fraction of observations, in each village, that own item X, for each of the unique items that are listed. The listen currently does this by doing a count for each item x village combination, and then dividing by the number of observations in each village (using `case_when()` with some magic numbers).

current code:
```r
percent_items <- interviews_plotting %>%
    gather(items, items_owned_logical, bicycle:no_listed_items) %>%
    filter(items_owned_logical) %>%
    count(items, village) %>%
    ## add a column with the number of people in each village
    mutate(people_in_village = case_when(village == "Chirodzo" ~ 39,
                                         village == "God" ~ 43,
                                         village == "Ruaca" ~ 49)) %>%
    mutate(percent = n / people_in_village)
```

I think this can be done a bit more naturally, and avoiding magic numbers, by using `summarize_at`:
```r
percent_items <- interviews_plotting %>%
    group_by(village) %>%
    summarize_at(vars(bicycle:no_listed_items), ~sum(.)/n()) %>%
    ungroup() %>%
    gather(items, percent, bicycle:no_listed_items)
```

Of course, we could also update the column selection using a variable, as in #191, as well as correcting the naming to use "proportion" instead of "percent", per #179

**Comment by atheobold** [comment]
@ha0ye I really appreciate your suggestion! I also would like to see the lesson move away from the use of hard-coded numbers, from a reproducibility standpoint. The current Data Wrangling lesson does not cover the `case_when()` function, but the `summarise()` function is included! Thus, I feel that teaching about the `summarize_at()` function as an extension to the `summarize()` function may lose fewer people than introducing the `case_when()` function. 

This addition, however, would make it necessary to:
1. state why the `vars()` function is being used  
2. state how the `~` and `.` are used in the proportion calculations
3. state why the table needs to be `ungroup`ed before being pivoted longer

I think the first point could be addressed by modifying the `pivot_longer()` code from the `tidyr` lesson to use the `vars()` function to select columns instead of creating a vector of names (e. g. `cols = vars(burntbricks, cement, muddaub, sunbricks)`). As for the other two points, those could be discussed within the `ggplot2` lesson.

**Comment by juanfung** [comment]
@ha0ye Are you still interested in submitting a PR for this issue? If not, no worries, and we will go ahead and close the issue

**Comment by ha0ye** [comment]
Oh, sure! I didn’t realize this point had evolved to where you were interested in a PR on it. I can definitely take a crack at it next week, and also incorporating the excellent suggestions from @atheobold.

**Comment by juanfung** [comment]
Sounds good thank you!
