### ISSUE TITLE
Explain data frames first

### ISSUE THREAD

**Issue by vguetler** [datacarpentry/r-socialsci#209]
---

The Starting with Data lesson objectives does not align with the lesson structure. It would be beneficial, to begin with explaining what data frames and tibbles are first before requiring learners to start loading the SAFI dataset.

**Comment by juanfung** [comment]
@vguetler This is a good point. I labeled this for discussion since it would entail a non-trivial revision of the lesson. 

My suggestion would be to move the entire "Presentation of the SAFI Data" to right after the introduction of tibbles under "What are data frames and tibbles." But I'm not sure if there is a better way to do this.

**Comment by vguetler** [comment]
@juanfung agreed. Beginning with "what are data frames and tibbles" first and then the explanation of the dataset before loading into R would be a great idea.
