### ISSUE TITLE
RFC: Migration to R 4.0

### ISSUE THREAD

**Issue by zkamvar** [datacarpentry/r-socialsci#222]
During the June Maintainer meeting, we asked for comments and experiences with the migration to R 4.0 so that we could create guidance for maintainers and instructors. We have drafted a short blog post (https://github.com/carpentries/carpentries.org/pull/830) to be released next week (2020-08-03) that describes our recommendations for migration. You can find a [preview of the blog post here](https://deploy-preview-830--stupefied-einstein-5bde90.netlify.app/blog/2020/08/r-4-migration/). **Please look over the blog posts and make comments by 2020-07-30 so that we can incoroporate any changes before the post goes live.**

To help identify the differences between R 3.6 and R 4.0, I have run this lesson in both versions and [posted the results](https://github.com/zkamvar/postmaul/blob/master/analysis.md#lesson-r-socialsci) that show the differences in output chunks and entire markdown files.

**Comment by atheobold** [comment]
@zkamvar I feel that many researchers, social science or otherwise, frequently work with categorical data. Thus, teaching different ways to work with categorical data should be of utmost importance in our curriculum, and should not relegated to supplementary material. While the default `stringsAsFactors = TRUE` was an easy way to introduce factors, I don't believe that this default provided a meaningful introduction to learners as to why factors are important. 

Factors are "a bit of a weird concept in `R`," and while they are useful for "statistical models," their importance dates back to when `R` users had to worry about the storage space of their computer. Given that today's netbook has no problem working with character data, I feel that we should reinvigorate the use of factors in our lessons. 

Since we don't teach statistical models in Carpentries lessons, motivations for the usefulness of factors could come through data wrangling and data visualization tasks. For example, when summarizing variables, the author may wish for a table of character data to have a specific ordering. Alternatively, when visualizing how a relationship changes over time, it may be inappropriate for time to be considered as continuous. I believe these motivations would provide learners with a more meaningful introduction to the usefulness of factors!

**Comment by zkamvar** [comment]
Thank you @atheobold for your input. Having dealt with categorical data in the past as both an R user and package author, I heartily agree with your statements. From what I can see, the r-socialsci lesson is not impacted by this change because it uses modern standards for reading in data with `{readr}`.

Would you be willing to add some suggestions to https://github.com/carpentries/carpentries.org/pull/830 that reflects these motivations and maybe point to https://datacarpentry.org/r-socialsci/02-starting-with-data/index.html#factors showing how this concept can be introduced without relying on the default parameters?

**Comment by atheobold** [comment]
@zkamvar I'd be happy to contribute, but I'm not quite sure what you are looking for. Would you like me to add these motivation to the Lesson Content section? Do you feel that the DC Starting with Data lesson can be linked to as an example of how to introduce factors?

**Comment by zkamvar** [comment]
>  I'm not quite sure what you are looking for.

I was thinking that your perspective was useful for maintainers who have to update their repositories, so adding a "for example" or "by the way" as a motivator for other maintainers would be helpful. Don't feel pressure to do so by any means, though. Also, if you do decide to contribute, you should add your name to the authors list (in alphabetical order). You can use GitHub's line commenting mechanism to suggest changes: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request (see step 6)

> Would you like me to add these motivation to the Lesson Content section? Do you feel that the DC Starting with Data lesson can be linked to as an example of how to introduce factors?

Yes and Yes :)

**Comment by atheobold** [comment]
@zkamvar -- my apologies for the late response! I have made the reviews to the sections you requested.
