### ISSUE TITLE
Fix alpha parameter in Box plot exercise solution

### ISSUE THREAD

**Issue by cengel** [datacarpentry/r-socialsci#229]
Episode 04-ggplot2.Rmd 

In the solution to the Boxplot exercise the alpha parameter needs to be **outside** the `aes` function, otherwise it will generate an entry in the legend.

change (line 284)

    interviews_plotting %>%
      ggplot(aes(x = respondent_wall_type, y = liv_count)) +
      geom_boxplot(alpha = 0) +
      geom_jitter(aes(alpha = 0.5, color = memb_assoc)) # <==

to

    interviews_plotting %>%
      ggplot(aes(x = respondent_wall_type, y = liv_count)) +
      geom_boxplot(alpha = 0) +
      geom_jitter(aes(color = memb_assoc), alpha = 0.5) # <==

**Comment by atheobold** [comment]
@cengel thanks for finding this error in the code! Since we introduce using `alpha` outside of `aes( )` on line 181, it makes complete sense to continue that practice here.

Would you like to create a pull request with this change, so that we can document your contributions to this lesson? If not, I am also happy to make this change.

**Comment by cengel** [comment]
@atheobold I submitted a pull request for this.
