### ISSUE TITLE
Website not building

### ISSUE THREAD

**Issue by juanfung** [datacarpentry/r-socialsci#254]
Tagging @fmichonneau as the expert. I am out of my depth with regard to the site build, but I got notified that it is [failing](https://github.com/datacarpentry/r-socialsci/runs/1156404499).

Additionally, several recent commits/PRs have not shown up on rendered site (I am guessing that this is because of the problems with travis and changes to site build instructions @fmichonneau made?).

**Comment by fmichonneau** [comment]
Yes there is a couple of issues with the site building. I think I'm close to figure it out but I ran out of time today. I'll check back tomorrow

**Comment by juanfung** [comment]
@fmichonneau Got it thanks!

**Comment by fmichonneau** [comment]
the site is now building correctly. I have switched to using GitHub Actions instead of Travis as the community support for R there is not as strong as it used to be and having everything done within GitHub is easier to manage. The logs for the builds are available under the 'Actions' button.

Pushes to the default branch (`master`) will lead to having the site built and deployed to the `gh-pages` branch for publishing the lesson.

Pull requests (and pushes to other branches) will lead to only having the site built which could be useful to detect errors.

Please let me know if you have any questions!

**Comment by juanfung** [comment]
Awesome thank you!
