### ISSUE TITLE
some points worth addressing while teaching this session

### ISSUE THREAD

**Issue by gurpreet2301** [datacarpentry/r-socialsci#256]
Hello,

There isn't any obvious description as to why we should be using -< as compared to =, to assign an object. The users are left wondering, so we need to add some specific advantages, and not just merely state that -< is preferable.

Further, going down to the section on "Data wrangling", somewhere in the middle, we bring in "Spreadsheet" lesson, and start pointing to that training module. Now, that is very confusing, as at the very beginning, no where it is mentioned that it is preferable to attend that session on Spreadsheet as well. This is quite misleading, given that we expect this to be a stand-alone session!

I hope this information is helpful.

Thanks,
Gurpreet Matharoo
(gurpreet.matharoo@ace-net.ca) 

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

**Comment by kelseygonzalez** [comment]
Hi @gurpreet2301, I see in lesson one that it says: "The arrow can be read as 3 goes into x. For historical reasons, you can also use `=` for assignments, but not in every context. Because of the slight differences in syntax, it is good practice to always use `<-` for assignments." Can you elaborate on where you feel more description could be added or how you would choose to explain this? 

In terms of the spreadsheet lesson, the typical Data Carpentry workshop consisted of a half day on Spreadsheets, a half day on Open Refine, and a full day on R. At least, that is how the workshop auto-organizes when you create a workshop website from the template. However, I see how this could be a little jarring since a) a lot of people may be using the workshop online and not know the format and b) many instructors focus solely on R for the two days. @juanfung, how do you feel if we were to remove the text that relies on the other workshop?

**Comment by gurpreet2301** [comment]
Hi @kelseygonzalez : Thanks for your comment! 

"For historical reasons, you can also use = for assignments, but not in every context. Because of the slight differences in syntax, it is good practice to always use <- for assignments."

The users ask questions about "what are those slight differences in syntax", and there is not enough documentation to comment on.  While what is written is true, the way it is written is slightly misleading for the first time presenter. Because one can do the exactly same thing with simple =, which comes more natural to users. So, we need some more power in the explanation as to why we discourage = for assigning. 

Does this makes sense...?

**Comment by atheobold** [comment]
Hi @gurpreet2301! Thanks for your comments, as these are things that I think many instructors (myself included) struggle with. I understand your desire to have additional verbiage around why assignment is preferred, however, I am concerned that these details are going to muddy the waters for first time R users. 

Historically, the assignment arrow dates back to S. In S, the `<-` was inspired by APL, which had a key for `<-`. 
At that time, `<-` was used for variable assignment, because `==` didn't exist for equality comparisons. Instead, equality was tested with `=`. So, you needed a different variable for assignment. 

Fast forward to today, there really are only a few mechanical reasons why `<-` is preferred over `=`. 
1. Assignment ranks higher in operator precedence than `=`. 
2. If you wish to perform variable assignment inside a function, `<-` is the only option. 

I believe both of these reasons will go over at least 80% of learners heads, and are thus not worth adding to the lesson. Alternatively, I think it is worthwhile to acknowledge the reasons why we prefer the `<-` syntax over `=`. 
1. They make it clear what direction the assignment is operating. 
2. They increase the read-ability of the code.

**Comment by gurpreet2301** [comment]
@atheobold : Hi Allison, Thank you very much for a very informative comment! That's precisely the information I was looking for. 

The historical perspective that you've described is quite informative, and I believe there is lot of incentive in having it, and for users knowing it. 

I understand your concern as far as technical/mechanical reasoning is concerned, but still, I do not think it is difficult for the users to understand it, if at all told...

We should certainly have those details in the instructors' notes for the sake of completeness, more so when such information is difficult to obtain, and is actually, gold!

Thanks, Gurpreet.

**Comment by juanfung** [comment]
@kelseygonzalez I'm okay removing the text re Spreadsheets.

@gurpreet2301 I was going to suggest this information fits in the instructor notes. How do you feel about this @kelseygonzalez @atheobold ?

**Comment by atheobold** [comment]
I'm happy with it being added to the instructor notes. I was mostly wondering what, if any, should be included in the body of the lesson. I think adding a short paragraph praising the readability of using `<-` could be wise?

**Comment by juanfung** [comment]
@atheobold I see. In the lesson, something short about readability should suffice. I think it's okay to add as long as it's short and does not distract from the lesson

**Comment by kelseygonzalez** [comment]
@atheobold it sounds like you'll be putting in a PR for your small section on `<-` - let me know when that PR goes in so that I can remove the language about spreadsheets in the dplyr lesson.

**Comment by gurpreet2301** [comment]
@kelseygonzalez , @atheobold , @juanfung : Thanks to all your messages. However, I noticed another mistake when we talk about pivot_longer. Specifically here: "This creates a dataframe with 262 rows (4 rows per interview respondent)."

In the original file, there are 131 rows, and when we do pivot_longer, we get 4 rows per interview respondent, that is 524 rows, not 262! That needs to be fixed as well.

Thanks,
Gurpreet.

**Comment by atheobold** [comment]
@gurpreet2301 -- thanks for pointing out that error. Would you be interested in making that change and submitting a pull request? That way there will be a record for your contributions!

**Comment by gurpreet2301** [comment]
@atheobold : Thanks, yes, I would like to do that. How to do a pull request, if that has not been done already?

**Comment by juanfung** [comment]
@gurpreet2301 Well, I was going to point to the contributing page but [it doesn't exist](https://datacarpentry.org/blob//CONTRIBUTING.md)!

It's pretty easy: 
- fork the repo
- create a dev branch on your fork
- push changes to dev branch on your fork
- on the GitHub page for your fork, you should see a notification about creating a PR for your changes
    - if not, just go to Pull Requests on lesson repo and you should be able to open the PR

**Comment by atheobold** [comment]
@gurpreet2301 -- I found the `pr_` functions from the ***usethis** package extremely useful when I learned about pull requests. Their set-up guide [(here)](https://usethis.r-lib.org/articles/articles/usethis-setup.html) is very useful, if you plan to continue contributing to these lessons. After that, I'd recommend the [article on pull requests](https://usethis.r-lib.org/articles/articles/pr-functions.html) for a step by step guide on how to fork, branch, commit, and push.
