### ISSUE TITLE
make sure readr >= 1.4.0

### ISSUE THREAD

**Issue by dafnevk** [datacarpentry/r-socialsci#269]
The `read_csv` command at the end of [episode 4](https://datacarpentry.org/r-socialsci/03-dplyr-tidyr/index.html) has been changed in pull request #266  to use the `file` argument instead of the deprecated `path` argument.
But that means that the installation of the package `readr` needs to be at least version 1.4.0. 
Can we add somewhere in the lesson to make sure to update this package? We only install `tidyverse`, but this does not automatically update the version of `readr` when there is an existing installation already.
I'm not sure what the best place would be, in the setup instructions, or as an extra comment to this line of code?

**Comment by juanfung** [comment]
@dafnevk Great catch! Since 1.4.0 is fairly new, perhaps we should not enforce version 1.4.0 yet. I don't believe we enforce package versions anywhere else. 

So perhaps it's best to change the argument back to `path`? In fact, the call should work without explicitly using the argument name (ie, `read_csv('path/to/file.csv')`
