### ISSUE TITLE
More explicit treatment of logical operators in dplyr's "filter" function

### ISSUE THREAD

**Issue by aranganath24** [datacarpentry/r-socialsci#299]
In the "Selecting columns and filtering rows" section of the "Data Wrangling with dplyr and tidyr" lesson (https://datacarpentry.org/r-socialsci/03-dplyr-tidyr/index.html) there is a code block that shows students that it is possible to select rows based on multiple conditions using dplyr’s “filter” function. That codeblock uses commas between the different arguments/conditions:

`
filter(interviews, village == "Chirodzo", rooms > 1, no_meals > 2)`

This is a fairly minor issue, but I was wondering whether it might be helpful to comment the code a bit more explicitly, and indicate that the commas in between the arguments are equivalent to "&" statements? This might seem self-evident, but it's plausible that someone new to this material could assume (prior to looking at the code output) that they are equivalent to "or" statements. On a related note, it might be nice to have an example showing a filtering operation based on an "or" condition, i.e. something like:

`
filter(interviews, rooms > 1|no_meals > 2)
`

**Comment by juanfung** [comment]
@aranganath24 Great catch. I would personally prefer using & instead of commas. Would you be willing to submit a PR with that change + an example with an or filter?

**Comment by aranganath24** [comment]
Hi @juanfung I'd be happy to do that, but I'm still somewhat new to this (this submission is part of my instructor checkout) and am a little confused by Step 1 in the "Using Github" section (https://github.com/datacarpentry/r-socialsci/blob/gh-pages/CONTRIBUTING.md). Step 2 (the Github workflow) makes total sense to me, but I could use some clarification on Step 1, just to make sure I do things correctly.

**Comment by juanfung** [comment]
@aranganath24 Great question. When you fork, you will notice that the repo has two branches (ignore dev branches): `master` and `gh-pages`. You should always merge changes to `master` not `gh-pages` (changes will be rendered automatically to `gh-pages`). 

* Minor note: we recently changed the name from `master` to `main` due to problems with rendering the page. So `master` doesn't exist anymore. Thank you for pointing this out, I will update the contributing page!

**Comment by aranganath24** [comment]
Thanks @juanfung I'll submit the PR tomorrow or early next week.

**Comment by atheobold** [comment]
> @aranganath24 Great catch. I would personally prefer using & instead of commas. Would you be willing to submit a PR with that change + an example with an or filter?

I actually prefer commas, since that is the built-in syntax for the **dplyr** verbs. I do, however, think that it would be nice to have a short blurb / example describing how a `,` operates the same as an `&`. This would be a great place to highlight how the `|` (or) can be used in the case where you want *either* statement to be satisfied.

**Comment by juanfung** [comment]
But there's no symbol analogous to `,` for an or statement? It may be unwise at this stage in the lesson to introduce two alternative notations for and statements, when one is very specific to dplyr.

**Comment by atheobold** [comment]
Nope. From my understanding, an OR statement requires a `|` and accepts nothing else. I think it may be a good idea to add a demonstration of an instance where you would want an "or." 

For example, you might want *both* the village of Chirodzo **and** Ruaca. Showing participants that the following code returns an empty dataframe would motivate why "or" (`|`) is another important data wrangling tool:

```filter(interviews, village == "Chirodzo", village == "Ruaca")```

**Comment by juanfung** [comment]
Right, I agree we should add an example illustrating OR. I just wonder whether it's worth showing both `&` and `,`.  I lean towards keeping it to `&`. I don't personally use `,` for constructing conditionals and worry it will just confuse learners to introduce two symbols, when one is very specific to dplyr.

**Comment by aranganath24** [comment]
Hi @juanfung and @atheobold it seems there's a consensus to add an "or" example, but not on whether to use "&" in the code, or keep the commas as is and provide some additional context in the comment. I think replacing the commas with "&" makes the code more readable, but keeping the commas could be pedagogically useful, since it alerts students to pay attention to differences between base R and the tidyverse with respect to syntax and other issues. 

If you let me know what you'd like to do regarding the & statement, I'll go ahead and make the change(s) and submit the PR. If you'd prefer to hold off on this for now, that's fine too!

**Comment by atheobold** [comment]
@aranganath24 -- To me, there is a fine balance between giving enough details but not too many details. Personally, I feel that adding a blurb about `&` goes toward the too many details side. Especially with people just learning to code in R, giving multiple approaches to do the same thing can be overwhelming. For that reason, I think it would be pedagogically better to stick with teaching the `,` for "and" `filter()`s. However, this conversation would benefit greatly from an example of why an "or" (`|`) condition would be needed in certain scenarios! 

If you are interested in writing up this type of change and putting it in a PR, we would love to incorporate your ideas!

**Comment by juanfung** [comment]
@atheobold A friendly debate! 😄 

I think we both agree that presenting multiple approaches for the same thing is unnecessary. 

Since we are now introducing `|` for OR operations, to me it seems natural to use `&` for AND operations. If the goal is for learners to continue using R on their own, I don't see why we wouldn't teach them the standard symbols that can be used in for control flow (eg, if else statements) rather than one specialized symbol for AND. 

It's minor, so happy either way. And appreciate @aranganath24 making the changes. Perhaps @kelseygonzalez has an opinion?
