### ISSUE TITLE
first use of function with side effects needs explaining?

### ISSUE THREAD

**Issue by steltenpower** [datacarpentry/r-socialsci#385]
On
levels(respondent_floor_type)[2] <- "brick"
a student said:"if you're not putting the result of the levels function into a variable, what's going on?"

**Comment by atheobold** [comment]
@steltenpower -- I would agree that this is a bit hard to understand for beginners. Personally, I would like to see this changed to some of the functions from the **forcats** package, such as `fct_relevel()`. Would you be interested in putting in a pull request improving this section of the workshop content?

**Comment by cgross95** [comment]
If there is still any interest in making these changes throughout the episode, I would be happy to contribute a pull request!

If so, the same section uses, e.g., in [line 395](https://github.com/datacarpentry/r-socialsci/blob/c89e0a2a1df5195f71fc188b76899c79d4ec5633/_episodes_rmd/02-starting-with-data.Rmd#L395)
`respondent_floor_type <- factor(respondent_floor_type, 
                                levels = c("earth", "cement"))
`
 to reorder the levels. If the **forcats** functions are preferable, would it be worth it to change this to 
`
respondent_floor_type <- fct_relevel(respondent_floor_type, 
                                             c("earth", "cement"))
`?

Since these commands use pretty much the same syntax, I would also understand if this change unnecessarily introduces the `fct_relevel` function and it would be better to leave it out.

**Comment by juanfung** [comment]
@cgross95 that would be great! Since we have not introduced **forcats** yet, I would prefer the former but if you are feeling ambitious perhaps we could have a callout with a quick intro to **forcats** illustrating the alternative, and maybe some other uses. Either way, I'm happy with the explicit use of `factor` as in line 395 for consistency.
