### ISSUE TITLE
Setup and references to Rtools for Windows installs

### ISSUE THREAD

**Issue by jjmedinaariza** [datacarpentry/r-socialsci#388]
The Setup section (https://datacarpentry.org/r-socialsci/setup.html) probably needs to be updated to make references to Rtools in the Windows instructions. As noted in the CRAN repository "Starting with R 4.0.0 (released April 2020), R for Windows uses a toolchain bundle called rtools4." As I discovered through a recent install in a new machine not having gone through this process gave me problems when installing "tidyverse", which is heavily used in this lesson. See details in CRAN: https://cran.r-project.org/bin/windows/Rtools/

**Comment by dkangsim-ehg** [comment]
I came to to this page to make a suggestion on adding a setup instruction for Rtools for Windows users. I am glad @jjmedinaariza raised created this issue.

**Comment by juanfung** [comment]
@dkangsim-ehg thanks! Would you be interested in submitting a PR per the discussion above?

**Comment by Osano1900** [comment]
This issue about the Rtools for the Windows setup should be looked at as discussed above and probably be closed if there is no need for the curriculum adjustment.

As discussed above, @atheobold suggested that @jjmedinaariza include sentences from R about Rtools in the Windows setup section; I haven't seen any sentences about Rtools added or even the response to the concern. Even though learners may not be interested in building packages at a workshop as mentioned by @atheobold, how about those learners who may encounter issues while installing tidyverse packages?

Also, @juanfung requested @dkangsim-ehg to pull requests for the discussion above. Was the PR submitted? I can't see any.

Otherwise, the maintainers should look into the Rtools issue and close it if there is no cause for alarm.

**Comment by Osano1900** [comment]
Thank you for your response @juanfung. I am not sure on how to go about this, that is, submitting a PR on Rtools. I think @jjmedinaariza or @dkangsim-ehg are better placed to submit the PR. Thank you.

**Comment by juanfung** [comment]
@jessesadler @eirini-zormpa : i vote to close the issue unless @jjmedinaariza or @dkangsim-ehg is willing/able to submit a PR. i am having trouble assessing whether this change is necessary and i am leaning towards "no" but welcome input from others.

**Comment by jessesadler** [comment]
@juanfung I agree about closing it.

**Comment by dkangsim-ehg** [comment]
Please close it.
