### ISSUE TITLE
Cross-check output for lubridate section in both 1.8 and 1.9

### ISSUE THREAD

**Issue by ndporter** [datacarpentry/r-socialsci#430]
The lubridate 1.9 update changes the output for some of the as_date() functions in the [lesson](https://datacarpentry.org/r-socialsci/02-starting-with-data/index.html#formatting-dates). 

Some of the code also doesn't produce the same output as the lesson in 1.8 - for example, `as_date(char_dates, format = "%m/%d/%y")` converts all dates to 2020 based on 2-digit year.

It's worth going through the whole section and cross-checking the output in multiple versions of lubridate and either specifying a version to have installed or noting where things may be different.

I would attach more specific examples but am having trouble upgrading.

**Comment by eirini-zormpa** [comment]
Thank you so much for the heads-up @ndporter ✨ Those examples would be super useful, could you explain what you mean when you say you're having trouble upgrading? Are you having issues with installing the latest lubridate version or are you having issues with pull requests etc. on GitHub?

**Comment by zkamvar** [comment]
I'm just popping in to comment that this is a perfect illustration of a situation where The Workbench is helpful.

The 2020 bug is in version 1.8, not 1.9.

The reason I know is because this is built with version 1.9: https://preview.carpentries.org/r-socialsci/02-starting-with-data.html#cb67 (as recorded in the [renv.lock file for r-socialsci](https://github.com/fishtree-attempt/r-socialsci/blob/5987100e75f6044f2e932d0898677f8f1980dab5/renv/profiles/lesson-requirements/renv.lock#L682-L692)) and it shows the correctly parsed years:


![output block with the dates "2012-07-31" "2014-08-09" "2016-04-30"](https://user-images.githubusercontent.com/3639446/214111593-50d049cd-9955-4f1a-8767-59a0fff220df.png)


To test the differences, I ran the following to download a copy of the lesson and roll back the version of lubridate (without affecting my own global version)

```r
# download the beta test from GitHub to my computer and open it
usethis::create_from_github("fishtree-attempt/r-socialsci")
# roll back lubridate to version 1.8.0
sandpaper::pin_version("lubridate@1.8.0")
# preview the lesson
sandpaper::serve()
```

![output block with the dates "2020-07-31" "2020-08-09" "2020-04-30"](https://user-images.githubusercontent.com/3639446/214111317-48df3ea0-e95d-4669-b216-71655866e90e.png)

**Comment by ndporter** [comment]
Perfect. I was going to try and do something similar once I wasn't mid-workshop but you beat me to it (and I do love the workbench version). At any rate, that is right and we do need to eventually adjust the lesson (maybe just remove that bit, since it's inconsistent)?
