### ISSUE TITLE
Quarto is the new R Markdown

### ISSUE THREAD

**Issue by bbartholdy** [datacarpentry/r-socialsci#459]
I am finding it harder to recommend learners use R Markdown after the workshops, given the recent development of [Quarto](https://quarto.org/). Quarto is supported in RStudio and is developed on many of the same principles as R Markdown, but has many more built-in features and a much closer integration with Pandoc, making it a better option for scientific publications/output. Given that the development of Quarto has become more stable (currently at v1.3), I think it would be a good time to potentially convert the R Markdown episode to Quarto (and given the similarities and built-in Knitr engine, it probably won't take a lot of effort). 

I think the learners will benefit more from learning Quarto than R Markdown, for example with the built-in cross-refs (previously the bookdown package was required) and the ability to use both R and Python (not relevant for this lesson, but could be interesting for the learners with prior Python experience).

This issue is submitted in collaboration with @cforgaci

**Comment by eirini-zormpa** [comment]
Hey Bjorn and Claudiu :sparkles:

**Comment by bbartholdy** [comment]
Hi Eirini! 👋 

Of course, looking forward to the response!

**Comment by juanfung** [comment]
@bbartholdy agree with @eirini-zormpa especially as it might be worth introducing quarto in other lessons. 

by the way, i had not heard of quarto and am looking forward to exploring it, so thank you!

**Comment by eirini-zormpa** [comment]
hi @bbartholdy and @cforgaci! After discussion with the CAC members, we think it's best to wait until the transition to R Markdown is further along and have a look at this again in ~6 months. For the time being we'll just add a note that Quarto exists and is the literate programming tool that will be actively developed by Posit instead of R Markdown.

I hope that's okay! I'll update this issue again when we discuss Quarto again :blush:

**Comment by bbartholdy** [comment]
Sounds good, thanks for the update Eirini!

**Comment by juanfung** [comment]
@eirini-zormpa thank you! closing for now
