### ISSUE TITLE
Installing packages

### ISSUE THREAD

**Issue by broadwym** [datacarpentry/r-socialsci#87]
Some feedback while reviewing lesson 00: Before we start: 

"Installing additional packages under the packages tab" might be a less-than-straightforward way to introduce new students to installing packages in R. Why not introduce the install.packages(" ") function as the major lesson objective (instead of as the side note)? 

I do see that install.packages("") is located under "Installing additional packages using R code", but imho it might be better served as the figurehead since the concept of library(" ") is introduced with ggplot2. 

An instructor might be able better explain the concept of CRAN with install.packages -> library functions. A nice mental link between the two concepts and hammer home the importance of documenting code. 

Cheers!

**Comment by eauer22** [comment]
I think it would also be helpful to include a few lines in this section about loading the libraries since that seems to only be briefly mentioned two lessons later in the starting with data lesson. Including this would help demonstrate the full package installation and use workflow. For example, we might add:

"After installing a package, use the `library()` function to load it for use. For example, to load the tidyverse package use `library(tidyverse)`. Packages only need to be installed once to remain in your package library. However, packages need to be loaded at the start of each R session before they can be used."
