### ISSUE TITLE
Translate to Spanish

### ISSUE THREAD

**Issue by martinolmos** [datacarpentry/r-socialsci#96]
Hi, 

Are there any plans to translate this lesson to Spanish. If so, I would love to collaborate. 

Best regards,

**Comment by fmichonneau** [comment]
There are no plans to translate this lesson in Spanish yet. It would be a welcome addition.

@orchid00 @raynamharris do you know if other people would be interested to help? (and if so, let me know before you start the translation work as we might test a different way of coordinating the translations).

**Comment by raynamharris** [comment]
I'm not aware of any interest yet, but I'm +1 for testing a new way to coordinate translations.

**Comment by orchid00** [comment]
I might say, @martinolmos @fmichonneau @raynamharris there's always interest. 
If anyone starts up a task on the slack channel, carpentries-es, I think volunteers will just come up

**Comment by martinolmos** [comment]
Ok! I'll do just that. How many volunteers do you think we need to start this project?

**Comment by fmichonneau** [comment]
please let me know before you start translating. We want to try out some dedicated tool to coordinate the translation. Thanks!

**Comment by orchid00** [comment]
YEs @martinolmos please keep @fmichonneau in the loop he is the Carpentries Development lead and he has been a key contact while doing other translations, more info here: https://github.com/Carpentries-ES/board
From my experience having 10 to 15 people for a lesson translations is a good number, but we pretty much did everything manually. I'm not sure about the new tool, which I would be happy to discuss if @fmichonneau wants to explain via zoom at some time (AEST) that I could attend. :)

**Comment by atheobold** [comment]
I will be meeting with Rayna Harris on November 9 to discuss how we can begin the process of translating our materials. We can revisit this TODO after that date.

**Comment by atheobold** [comment]
Alright, here's a debrief from my meeting with @raynamharris: 

- As @fmichonneau eluded to, there are new tools that are being used to coordinate the Spanish lessons with their English counterparts. From my understanding, this is to facilitate easier updating between the two lessons, so some of the "fixes" can be done by AI. 
- Some of the Spanish lessons are being served at the same web address as the English lessons, with an -es added to the end (e.g. https://swcarpentry.github.io/r-novice-gapminder vs. https://swcarpentry.github.io/r-novice-gapminder-es/). It seems that Software Carpentry is the only group to have Spanish versions of all of their lessons, so I'm not sure if the other Spanish lessons are being systematically hosted in a similar way. 
- The Translations Slack channel would possibly be the best place for us to recruit individuals to assist @martinolmos in translating this lesson. 

Since our team is not familiar with the new tool being used to coordinate human translations with AI, I'm not sure if this Issue needs to remain in this repo. I'm wondering if it would be a better idea to reach out through Slack and see if there are other volunteers interested in helping @martinolmos. If a team assembles, perhaps they should coordinate with @fmichonneau to utilize the new translation tool? 

Happy to hear other's thoughts!

**Comment by fmichonneau** [comment]
Yes, I think that gauging interest to translate the lesson by sending a message on the Slack channel would be a good place to start.

**Comment by kelseygonzalez** [comment]
@fmichonneau I've had two Spanish speaking friends express interest in helping out with the carpentries translation efforts. How can they join in?

**Comment by atheobold** [comment]
As seen through this conversation, this topic is outside of the scope of this lesson. Thus, we have decided to close this Issue. If you would like to get involved in the translation efforts, please contact @fmichonneau or @martinolmos!
